# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chora < Formula
  desc "Chora CLI — local agent runtime and management tool for the Chora platform"
  homepage "https://github.com/Chora-Inc/chora"
  version "0.3.36"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.36/chora-cli-0.3.36-darwin-amd64.tar.gz"
      sha256 "715b17a36af7bd4164742bdcded4561a9af6cf8f2ab62a7f61c0d3c1d9d8f7a8"

      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.36/chora-cli-0.3.36-darwin-arm64.tar.gz"
      sha256 "77b94564397f3510eef37693515589a8abf69d76cf372a9bfd9a39ada8023d16"

      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.36/chora-cli-0.3.36-linux-amd64.tar.gz"
      sha256 "c5b9e83d0ffe72ab7ee6e92e9530c57a9fa1a953bed4544fbb8be9a3fee47ec7"
      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.36/chora-cli-0.3.36-linux-arm64.tar.gz"
      sha256 "c1c75d205566c9449ae58bdd5aafc08468089e68d262d157568797254aff52f2"
      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  test do
    system "#{bin}/chora", "version"
  end
end
