# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chora < Formula
  desc "Chora CLI — local agent runtime and management tool for the Chora platform"
  homepage "https://github.com/Chora-Inc/chora"
  version "0.3.48"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.48/chora-cli-0.3.48-darwin-amd64.tar.gz"
      sha256 "a3a899193d9e5f90a9db3b724879111dcc8c2f88afa131729fff9ffaf1487b70"

      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.48/chora-cli-0.3.48-darwin-arm64.tar.gz"
      sha256 "0c4250089c2d63d41ec0e4169f539fd4fa4a834b5bb5ed3e064302d6cc41ea5f"

      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.48/chora-cli-0.3.48-linux-amd64.tar.gz"
      sha256 "c801a870f56fd06c7ec7d6475de53d9bd6eaf700939aad5aa7327d1f2247702f"
      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.48/chora-cli-0.3.48-linux-arm64.tar.gz"
      sha256 "d5dc08979209900753626f32bbd5b54ea5df1ce815cb02e9d7c3cb88c21c9fbe"
      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  test do
    system "#{bin}/chora", "version"
  end
end
