# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chora < Formula
  desc "Chora CLI — local agent runtime and management tool for the Chora platform"
  homepage "https://github.com/Chora-Inc/chora"
  version "0.3.46"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.46/chora-cli-0.3.46-darwin-amd64.tar.gz"
      sha256 "a16508262d0e6524a4d5ee29d2e74ca183b7876b3a793e8c62bb5840362ec6ae"

      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.46/chora-cli-0.3.46-darwin-arm64.tar.gz"
      sha256 "3d0dd0ff59898b1a7d265d41cfd3e6385713168a837018cffed1dfe893a79070"

      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.46/chora-cli-0.3.46-linux-amd64.tar.gz"
      sha256 "698da1497447090432c6edb98b708e57721c5c204d74f61cd89fab445bf2ab33"
      define_method(:install) do
        bin.install "chora"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chora-Inc/Chora-Release/releases/download/v0.3.46/chora-cli-0.3.46-linux-arm64.tar.gz"
      sha256 "1ce37b9b7f97993f15be304715a3f2b76c033aaf7a42f8414adbd9b8831a2141"
      define_method(:install) do
        bin.install "chora"
      end
    end
  end

  test do
    system "#{bin}/chora", "version"
  end
end
